### PR TITLE
Ready to merge laptime-overview data binding from GeneralTabDev-Branch

### PR DESCRIPTION
**Pull request by FelixStarke**
Please review :)

### CODE REVIEW

**Comment by ChristopherKlammt** [comment]
Looking very good, I tested it and everything is working. 
Good Work!

**Review by huebnerl — COMMENTED** [review]
Almost okay.

**Review by ChristopherKlammt — COMMENTED** [review]
Looking very good, I tested it and everything is working.
Good Work!

**Comment by ArneSchulze** [comment]
Hey guys,

i must admit that you've made great progress in the last few weeks! Keep on going like that!

Cheers
ArneSchulze

**Pull request merged**
